version: "3.9"

services:
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - published: 4000
        target: 4000
    networks:
      - graphql
    environment:
      PORT: 4000
      GRPC_SERVICE_URL_CORE: grpc-core:5000
      GRPC_SERVICE_URL_CONTENT: grpc-content:5000
      GRPC_SERVICE_URL_SEARCH: grpc-search:5000
      GRPC_SERVICE_URL_BOOKCOVER: grpc-bookcover:5000

  grpc-core:
    build:
      context: ./grpc-services/core
      dockerfile: Dockerfile
    networks:
      - grpc-core
    environment:
      CONNECTION_URL: localhost:5000

  grpc-search:
    build:
      context: ./grpc-services/search
      dockerfile: Dockerfile
    networks:
      - grpc-search
    environment:
      CONNECTION_URL: localhost:5000

  grpc-bookcover:
    build:
      context: ./grpc-services/bookcover
      dockerfile: Dockerfile
    networks:
      - grpc-bookcover
    environment:
      CONNECTION_URL: localhost:5000

networks:
  graphql:

  grpc-core:
  grpc-search:
  grpc-bookcover:
