version: "3.9"

services:
  mysql:
    image: mysql:8.0
    ports:
      - published: $MYSQL_PORT
        target: 3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

  adminer:
    image: adminer:4-standalone
    ports:
      - published: $ADMINER_PORT
        target: 8080
