version: "3.8"

services:
  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - published: $IMGPROXY_PORT
        target: 8080
    environment:
      IMGPROXY_KEY: $IMGPROXY_KEY
      IMGPROXY_SALT: $IMGPROXY_SALT
