name: CI(grpc-core)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/ci-core.yml
      - grpc-services/core/**

defaults:
  run:
    working-directory: grpc-services/core

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: grpc-services/core
      - run: yarn run lint:eslint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: grpc-services/core
      - run: yarn run generate
      - run: yarn run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: grpc-services/core
      - run: yarn run generate
      - run: yarn run build
