name: CI(graphql-gateway)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/ci-graphql-gateway.yml
      - graphql-gateway/**

defaults:
  run:
    working-directory: graphql-gateway

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-gateway
      - run: yarn run lint:eslint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-gateway
      - run: yarn run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-gateway
      - run: yarn run build
