name: CI(graphql-content-services)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/ci-graphql-content-services.yml
      - graphql-services/content/**

defaults:
  run:
    working-directory: graphql-services/content

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-services/content
      - run: yarn run lint:eslint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-services/content
      - run: yarn run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: graphql-services/content
      - run: yarn run build
